// ASMI_CV.v

// Generated using ACDS version 20.1 720

`timescale 1 ps / 1 ps
module ASMI_CV (
		input  wire [23:0] addr,           //           addr.addr
		input  wire        bulk_erase,     //     bulk_erase.bulk_erase
		output wire        busy,           //           busy.busy
		input  wire        clkin,          //          clkin.clk
		output wire        data_valid,     //     data_valid.data_valid
		input  wire [7:0]  datain,         //         datain.datain
		output wire [7:0]  dataout,        //        dataout.dataout
		input  wire        fast_read,      //      fast_read.fast_read
		output wire        illegal_erase,  //  illegal_erase.illegal_erase
		output wire        illegal_write,  //  illegal_write.illegal_write
		input  wire        rden,           //           rden.rden
		input  wire        reset,          //          reset.reset
		input  wire        sector_erase,   //   sector_erase.sector_erase
		input  wire        sector_protect, // sector_protect.sector_protect
		input  wire        shift_bytes,    //    shift_bytes.shift_bytes
		input  wire        wren,           //           wren.wren
		input  wire        write           //          write.write
	);

	ASMI_CV_asmi_parallel_0 asmi_parallel_0 (
		.clkin          (clkin),          //          clkin.clk
		.fast_read      (fast_read),      //      fast_read.fast_read
		.rden           (rden),           //           rden.rden
		.addr           (addr),           //           addr.addr
		.write          (write),          //          write.write
		.datain         (datain),         //         datain.datain
		.shift_bytes    (shift_bytes),    //    shift_bytes.shift_bytes
		.sector_protect (sector_protect), // sector_protect.sector_protect
		.sector_erase   (sector_erase),   //   sector_erase.sector_erase
		.bulk_erase     (bulk_erase),     //     bulk_erase.bulk_erase
		.wren           (wren),           //           wren.wren
		.reset          (reset),          //          reset.reset
		.dataout        (dataout),        //        dataout.dataout
		.busy           (busy),           //           busy.busy
		.data_valid     (data_valid),     //     data_valid.data_valid
		.illegal_write  (illegal_write),  //  illegal_write.illegal_write
		.illegal_erase  (illegal_erase)   //  illegal_erase.illegal_erase
	);

endmodule
