// SPDX-License-Identifier: GPL-2.0-or-later
//
// Zeus — OpenHPSDR Protocol-1 / Protocol-2 client.
// Copyright (C) 2025-2026 Brian Keating (EI6LF),
//                         Douglas J. Cerrato (KB2UKA),
//                         Christian Suarez (N9WAR), and contributors.
//
// Zeus is distributed WITHOUT ANY WARRANTY; see the GNU General Public
// License for details.
//
// GENERATED — the ZeusMidiCommand enum, the UI catalogue, and the dispatch
// switch are produced from one shared command table so the three never drift.
// Full Thetis-parity command surface (PureSignal arm DELIBERATELY excluded).

using System.Collections.Generic;
using Zeus.Contracts;

namespace Zeus.Server.Midi;

/// <summary>One row of the MIDI command catalogue surfaced via
/// <c>GET /api/midi/commands</c> so the settings panel can list every
/// command with its human label, expected control type, toggle flag, and
/// whether it is wired to a real seam (vs parity-only).</summary>
public sealed record MidiCommandInfo(
    ZeusMidiCommand Command,
    string Label,
    MidiControlType ControlType,
    bool IsToggle,
    bool Supported);

/// <summary>The static, generated MIDI command catalogue (full Thetis
/// parity). Order matches the <see cref="ZeusMidiCommand"/> enum.</summary>
public static class MidiCommandCatalog
{
    public static readonly IReadOnlyList<MidiCommandInfo> All = new MidiCommandInfo[]
    {
        new(ZeusMidiCommand.VfoAtoB, "VfoA To B", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.VfoBtoA, "VfoB To A", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.VfoSwap, "Vfo Swap", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.RitOnOff, "Rit On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.XitOnOff, "Xit On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.RIT_clear, "RIT Clear", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.XIT_clear, "XIT Clear", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.RIT_inc, "RIT", MidiControlType.Wheel, false, true),
        new(ZeusMidiCommand.XIT_inc, "XIT", MidiControlType.Wheel, false, true),
        new(ZeusMidiCommand.BandUp, "Band Up", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.BandDown, "Band Down", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band160m, "Band 160m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band80m, "Band 80m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band60m, "Band 60m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band40m, "Band 40m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band30m, "Band 30m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band20m, "Band 20m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band17m, "Band 17m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band15m, "Band 15m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band12m, "Band 12m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band10m, "Band 10m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band6m, "Band 6m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band2m, "Band 2m", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.Band160mRX2, "RX2 Band 160m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band80mRX2, "RX2 Band 80m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band60mRX2, "RX2 Band 60m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band40mRX2, "RX2 Band 40m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band30mRX2, "RX2 Band 30m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band20mRX2, "RX2 Band 20m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band17mRX2, "RX2 Band 17m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band15mRX2, "RX2 Band 15m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band12mRX2, "RX2 Band 12m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band10mRX2, "RX2 Band 10m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band6mRX2, "RX2 Band 6m", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Band2mRX2, "Band2mRX2", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.Rx2BandUp, "Rx2 Band Up", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Rx2BandDown, "Rx2 Band Down", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.ChangeFreqVfoA, "Change Freq Vfo A", MidiControlType.Wheel, false, true),
        new(ZeusMidiCommand.ChangeFreqVfoB, "Change Freq Vfo B", MidiControlType.Wheel, false, true),
        new(ZeusMidiCommand.TuningStepUp, "Tuning Step Up", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.TuningStepDown, "Tuning Step Down", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.MoveVFOADown100Khz, "Move VFOA Down 100Khz", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.MoveVFOAUp100Khz, "Move VFOA Up 100Khz", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.MoveVFOBDown100Khz, "Move VFOB Down 100Khz", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.MoveVFOBUp100Khz, "Move VFOB Up 100Khz", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.CTunOnOff, "Click Tune On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.RX2CTunOnOff, "RX2 CTUN On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.LockVFOOnOff, "Toggle VFO Lock - A,both,off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.LockVFOAOnOff, "Lock VFO A", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.LockVFOBOnOff, "Lock VFO B", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.VfoSyncOnOff, "Vfo Sync On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.MultiStepVfoA, "Multi Step Vfo A", MidiControlType.Wheel, false, true),
        new(ZeusMidiCommand.SwapVFOWheels, "Swap VFO Wheels", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.ToggleVFOWheel, "Toggle Wheel to VFOA/VFOB", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.Rx1ModeNext, "Rx1 Mode Next", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Rx1ModePrev, "Rx1 Mode Prev", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Rx2ModeNext, "RX2 Mode Next", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Rx2ModePrev, "RX2 Mode Prev", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.ModeSSB, "Mode SSB", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.ModeLSB, "Mode LSB", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.ModeUSB, "Mode USB", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.ModeDSB, "Mode DSB", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.ModeCW, "Mode CW", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.ModeCWL, "Mode CWL", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.ModeCWU, "Mode CWU", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.ModeFM, "Mode FM", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.ModeAM, "Mode AM", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.ModeDIGU, "Mode DIGU", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.ModeSPEC, "Mode SPEC", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.ModeDIGL, "Mode DIGL", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.ModeSAM, "Mode SAM", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.ModeDRM, "Mode DRM", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.Rx1FilterWider, "Rx1 Filter Wider", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Rx1FilterNarrower, "Rx1 Filter Narrower", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Rx2FilterWider, "RX2 Filter Wider", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Rx2FilterNarrower, "RX2 Filter Narrower", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.FilterHigh, "Filter High", MidiControlType.Wheel, false, true),
        new(ZeusMidiCommand.FilterLow, "Filter Low", MidiControlType.Wheel, false, true),
        // FilterShift is dispatched as a relative encoder step (see
        // MidiCommandDispatcher: shift = delta * 10) — cataloguing it as
        // KnobOrSlider silently no-ops on any absolute-control binding.
        new(ZeusMidiCommand.FilterShift, "Filter Shift", MidiControlType.Wheel, false, true),
        new(ZeusMidiCommand.FilterBandwidth, "FilterBandwidth", MidiControlType.Wheel, false, true),
        new(ZeusMidiCommand.TxFilterHigh, "TX Filter high", MidiControlType.Wheel, false, true),
        new(ZeusMidiCommand.TxFilterLow, "TX Filter low", MidiControlType.Wheel, false, true),
        new(ZeusMidiCommand.ApfOnOff, "Audio Peak Filter On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.ApfFreq, "Audio Peak Filter Tune", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.ApfBandwidth, "Audio Peak Filter Bandwidth", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.ApfGain, "Audio Peak Filter Gain", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.ApfTypeDoublePole, "APF Type Double Pole", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.ApfTypeMatched, "APF Type Matched", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.ApfTypeGaussian, "APF Type Gaussian", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.ApfTypeBiquad, "APF Type Biquad", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.AgcModeUp, "AGC Mode Up", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.AgcModeDown, "AGC Mode Down", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.Rx2AgcModeUp, "RX2 AGC Mode Up", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.Rx2AgcModeDown, "RX2 AGC Mode Down", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.AgcModeKnob, "AGC Mode", MidiControlType.KnobOrSlider, false, true),
        new(ZeusMidiCommand.Rx2AgcModeKnob, "RX2 AGC Mode", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.Rx1AgcLevel, "RX1 AGC Level", MidiControlType.KnobOrSlider, false, true),
        new(ZeusMidiCommand.Rx2AgcLevel, "RX2 AGC Level", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.Rx1AgcLevelInc, "RX1 AGC Level Incr", MidiControlType.Wheel, false, true),
        new(ZeusMidiCommand.Rx2AgcLevelInc, "RX2 AGC Level Incr", MidiControlType.Wheel, false, false),
        new(ZeusMidiCommand.Nr1OnOff, "Noise Reduction 1 On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.Nr2OnOff, "Noise Reduction 2 On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.Nr3OnOff, "Noise Reduction 3 On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.Nr4OnOff, "Noise Reduction 4 On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.Nr4Amount, "Noise Reduction 4 Amount", MidiControlType.KnobOrSlider, false, true),
        new(ZeusMidiCommand.Rx2Nr1OnOff, "Rx2 Noise Reduction1 On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.Rx2Nr2OnOff, "Rx2 Noise Reduction2 On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.Rx2Nr3OnOff, "Rx2 Noise Reduction 3 On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.Rx2Nr4OnOff, "Rx2 Noise Reduction 4 On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.Rx2Nr4Amount, "Rx2 Noise Reduction 4 Amount", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.Rx1Nb1OnOff, "Rx1 Noise Blanker1 On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.Rx1Nb2OnOff, "Rx1 Noise Blanker2 On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.Rx2Nb1OnOff, "Rx2 Noise Blanker1 On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.Rx2Nb2OnOff, "Rx2 Noise Blanker2 On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.AutoNotchOnOff, "Auto Notch On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.Rx2AutoNotchOnOff, "RX2 Auto Notch On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.SpectralNbOnOff, "Spectral Noise Blanker On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.Rx2SpectralNbOnOff, "Rx2 Spectral Noise Blanker On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.SquelchOnOff, "Squelch On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.SquelchLevel, "Squelch", MidiControlType.KnobOrSlider, false, true),
        new(ZeusMidiCommand.Rx2SquelchOnOff, "RX2 Squelch On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.Rx2SquelchLevel, "RX2 Squelch Level", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.BinauralOnOff, "Binaural On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.Rx1AutoAgc, "RX1 Auto AGC compensation", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.Rx2AutoAgc, "RX2 Auto AGC compensation", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.SetAfGain, "AF Gain", MidiControlType.KnobOrSlider, false, true),
        new(ZeusMidiCommand.VolumeVfoA, "Volume VfoA", MidiControlType.KnobOrSlider, false, true),
        new(ZeusMidiCommand.VolumeVfoB, "Volume VfoB", MidiControlType.KnobOrSlider, false, true),
        new(ZeusMidiCommand.VolumeVfoAIncr, "Volume VfoA Incr", MidiControlType.Wheel, false, true),
        new(ZeusMidiCommand.VolumeVfoBIncr, "Volume VfoB Incr", MidiControlType.Wheel, false, true),
        new(ZeusMidiCommand.Rx2Volume, "RX2 Volume", MidiControlType.KnobOrSlider, false, true),
        new(ZeusMidiCommand.MuteOnOff, "Mute On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.Rx2MuteOnOff, "RX2 Mute On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.MonOnOff, "MON On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.MicGain, "MicGain", MidiControlType.KnobOrSlider, false, true),
        new(ZeusMidiCommand.PreAmpSettingsKnob, "PreAmp Setting", MidiControlType.KnobOrSlider, false, true),
        new(ZeusMidiCommand.TxAfMonitor, "TX AF Monitor", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.VacOnOff, "VAC On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.Vac2OnOff, "VAC 2 On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.IqToVac, "Rx1 IQ To VAC", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.IqToVacRx2, "Rx2 IQ to VAC", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.VacGainRx, "VAC Gain RX", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.VacGainTx, "VAC Gain TX", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.Vac2GainRx, "VAC2 Gain RX", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.Vac2GainTx, "VAC2 Gain TX", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.PanCenter, "Pan Center", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.PanSlider, "Pan", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.PanSliderInc, "Pan", MidiControlType.Wheel, false, false),
        new(ZeusMidiCommand.RatioMainSubRx, "Ratio Main Sub Rx", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.Rx2Pan, "Stereo Balance RX2 (PAN)", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.AudioAmpOnOff, "Audio Amp On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.MoxOnOff, "MOX On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.TunOnOff, "Tune On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.VoxOnOff, "VOX On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.DriveLevel, "DriveLevel", MidiControlType.KnobOrSlider, false, true),
        new(ZeusMidiCommand.DriveLevelInc, "Drive Level Increment", MidiControlType.Wheel, false, true),
        new(ZeusMidiCommand.TunPowerLevel, "TUN Power Level", MidiControlType.KnobOrSlider, false, true),
        new(ZeusMidiCommand.DexpOnOff, "DEXP On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.DexpThreshold, "DEXP Threshold", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.CompanderOnOff, "Compander On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.RxEqOnOff, "RX EQ On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.TxEqOnOff, "TX EQ On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.TwoToneOnOff, "2Tone On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.ExternalPaOnOff, "External PA On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.TunerOnOff, "Tuner On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.TunerBypassOnOff, "Tuner Bypass", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.SplitOnOff, "Split On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.QuickSplitOnOff, "Quick Split On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.QuickSplitAndSplitOnOff, "Quick Split + VFO Split On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.ToggleTx, "Toggle TX VFOA VFOB", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.CpdrLevel, "CPDRLevel", MidiControlType.KnobOrSlider, false, true),
        new(ZeusMidiCommand.VoxGain, "VOXGain", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.CwSpeed, "CW Speed", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.CwSpeedInc, "CW Speed Incr", MidiControlType.Wheel, false, false),
        new(ZeusMidiCommand.CwBreakIn, "Manual or Semi Break-In", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.CwQsk, "Semi or QSK Break-In", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.CwxMacro1, "CW XMacro 1", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.CwxMacro2, "CWX Macro 2", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.CwxMacro3, "CWX Macro 3", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.CwxMacro4, "CWX Macro 4", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.CwxMacro5, "CWX Macro 5", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.CwxMacro6, "CWX Macro 6", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.CwxMacro7, "CWX Macro 7", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.CwxMacro8, "CWX Macro 8", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.CwxMacro9, "CWX Macro 9", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.CwxStop, "CWX Stop", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.CwxKey, "CWX Key", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.CwxPtt, "CWX PTT", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.StartOnOff, "Start On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.CloseConsole, "Close Thetis", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.ZoomInc, "Zoom Inc", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.ZoomDec, "Zoom Dec", MidiControlType.Button, false, true),
        new(ZeusMidiCommand.ZoomSliderInc, "Zoom", MidiControlType.Wheel, false, true),
        new(ZeusMidiCommand.ZoomSliderFix, "Zoom", MidiControlType.KnobOrSlider, false, true),
        new(ZeusMidiCommand.DisplayAverage, "Display Average", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.DisplayPeak, "Display Peak", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.DisplayTxFilter, "Display Tx Filter", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.DisplayModeNext, "Display Mode Next", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.DisplayModePrev, "Display Mode Prev", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.WaterfallLowLimit, "Waterfall Low Limit", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.WaterfallHighLimit, "Waterfall High Limit", MidiControlType.KnobOrSlider, false, false),
        new(ZeusMidiCommand.MultiRxOnOff, "Multi Rx On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.RX2OnOff, "RX2 On Off", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.Rx2PreAmpOnOff, "Rx2 Pre Amp On Off", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.DiversityEnable, "Diversity Enable", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.DiversityPhase, "Diversity Phase", MidiControlType.Wheel, false, true),
        new(ZeusMidiCommand.DiversityGain, "Diversity Gain", MidiControlType.Wheel, false, true),
        new(ZeusMidiCommand.DiversityReference, "Diversity RX Reference", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.DiversitySource, "Diversity RX Source", MidiControlType.Button, true, true),
        new(ZeusMidiCommand.DiversityFormOpen, "Diversity Form Open", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.ZeroBeatPress, "Zero Beat", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.QuickModeSave, "Quick Mode Save", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.QuickModeRestore, "Quick Mode Restore", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.QuickPlayOnOff, "Quick Play Wave File", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.QuickRecOnOff, "Quick Rec Wave File", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.ZoomToBandStore, "Zoom To Band Store", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.ZoomToBandRecall, "Zoom To Band Recall", MidiControlType.Button, false, false),
        // VFO wheel sensitivity is not wired to a tune path (no divisor is read);
        // parity-only until that scaling exists, so the UI does not advertise a
        // live control that does nothing.
        new(ZeusMidiCommand.MidiMessagesPerTuneStepUp, "Increase wheel rotation per VFO tune step", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.MidiMessagesPerTuneStepDown, "Decrease wheel rotation per VFO tune step", MidiControlType.Button, false, false),
        new(ZeusMidiCommand.MidiMessagesPerTuneStepToggle, "VFO Wheel Sensitivity High/Low Toggle", MidiControlType.Button, true, false),
        new(ZeusMidiCommand.ESCFormOnOff, "ESC Form On Off", MidiControlType.Button, true, false),
    };

    /// <summary>Commands that key the transmitter. These may only be driven by a
    /// discrete button press — a continuous knob/wheel binding would dispatch on
    /// every tick and thrash the PA on/off, so the routing layer refuses to send
    /// a non-button control to one of these.</summary>
    public static bool IsTxKeying(ZeusMidiCommand cmd) => cmd is
        ZeusMidiCommand.MoxOnOff or
        ZeusMidiCommand.TunOnOff or
        ZeusMidiCommand.TwoToneOnOff;
}
